# -*- coding: utf-8 -*-
"""Name/label EN→VI maps and roman-numeral helpers."""
from __future__ import annotations

import re

ROMAN = re.compile(r"\s+(I{1,3}|IV|V|VI{0,3}|IX|X)$")

# Base phrases without trailing roman numerals
_BASE_NAMES: dict[str, str] = {
    "Improved Work Area": "Khu làm việc cải tiến",
    "Extra Food Storage": "Kho lương thực thêm",
    "Extra Gold Storage": "Kho vàng thêm",
    "Extra Iron Storage": "Kho sắt thêm",
    "Extra Wood Storage": "Kho gỗ thêm",
    "Extra Stone Storage": "Kho đá thêm",
    "Extra Magic Storage": "Kho phép thuật thêm",
    "Skilled Labour": "Lao động lành nghề",
    "Weapon Forging": "Rèn vũ khí",
    "Armour Forging": "Rèn giáp",
    "Tool Forging": "Rèn công cụ",
    "Craftsmanship": "Thủ công tinh xảo",
    "Seafaring": "Hải trình",
    "Trade Storage": "Kho giao thương",
    "Cargo Holds": "Khoang hàng",
    "Wayfaring": "Lữ hành",
    "Wagon Yard": "Bãi xe",
    "Guest Rooms": "Phòng khách",
    "Minstrels": "Nhạc công",
    "Critical Success": "Thành công lớn",
    "Inspirational Leadership": "Lãnh đạo truyền cảm hứng",
    "Dedicated Leader": "Lãnh đạo tận tâm",
    "Magical Tool Crafting Expertise": "Chuyên môn chế tạo dụng cụ phép",
    "Enchant Weapons": "Phù phép vũ khí",
    "Enchant Armour": "Phù phép giáp",
    "Recent Starvation": "Nạn đói gần đây",
}

_FIXED_NAMES: dict[str, str] = {
    # Achievements
    "Coin for the Realm": "Tiền cho vương quốc",
    "A Place to Call Home": "Nơi gọi là nhà",
    "My Home and Castle": "Nhà và lâu đài của tôi",
    "Rising Challenge": "Thử thách ngày càng cao",
    "Gentle Rule": "Cai trị êm đềm",
    "Against the Odds": "Nghịch cảnh",
    "Steady Hands": "Tay vững vàng",
    "Standing Strong": "Đứng vững",
    "First Contact": "Tiếp xúc đầu tiên",
    "A Merchant's Tale": "Chuyện thương nhân",
    "Flawless Victory": "Chiến thắng hoàn hảo",
    "Master Builder": "Bậc thầy xây dựng",
    "A Kingdom is Born": "Vương quốc ra đời",
    "We love it here!": "Chúng tôi yêu nơi này!",
    "Steadfast Resolve": "Ý chí kiên định",
    "A City Rises": "Thành phố vươn mình",
    "Hearth and Hamlet": "Hearth and Hamlet",
    "He's a Wizard": "Ông ấy là pháp sư",
    "Educated Minds": "Trí tuệ được khai sáng",
    "Humble Beginning": "Khởi đầu khiêm tốn",
    "Walls of Stone": "Tường đá",
    "Ancient Evil": "Tà ác cổ xưa",
    "Merchant Kingdom": "Vương quốc thương nhân",
    "Just Pay It With Magic": "Cứ trả bằng phép thuật",
    # Items / shop
    "Grand Transmutation": "Đại chuyển hóa",
    "Battle Loot: Plants": "Chiến lợi phẩm: Thực vật",
    "Battle Loot: Goblin": "Chiến lợi phẩm: Goblin",
    "Battle Loot: Orc": "Chiến lợi phẩm: Orc",
    "Battle Loot: Animals": "Chiến lợi phẩm: Động vật",
    "Battle Loot: Human": "Chiến lợi phẩm: Người",
    "Battle Loot: Undead": "Chiến lợi phẩm: Undead",
    "Battle Loot: Demon": "Chiến lợi phẩm: Quỷ",
    "Preserving Salts": "Muối bảo quản",
    "Herbal Remedies": "Thuốc thảo mộc",
    "Iron Finding Potion": "Thuốc tìm sắt",
    "Stone Breaking Powder": "Bột phá đá",
    "Fertility Elixirs": "Tiên dược sinh sản",
    "Gold Finding Potion": "Thuốc tìm vàng",
    "Elixir of Vitality": "Tiên dược sinh lực",
    "Healing Potions": "Thuốc hồi máu",
    "Philosopher's Brew": "Thuốc giả kim",
    "Convert Iron to Gold": "Đổi sắt thành vàng",
    "Timber Growth Potion": "Thuốc tăng trưởng gỗ",
    "Heaven's Blessing": "Phước lành thiên đường",
    "Heaven’s Blessing": "Phước lành thiên đường",
    "Advanced Blueprint Design": "Thiết kế bản vẽ nâng cao",
    "Expert Blueprint Design": "Thiết kế bản vẽ chuyên gia",
    "Legendary Blueprint Design": "Thiết kế bản vẽ huyền thoại",
    "Master Blueprint Design": "Thiết kế bản vẽ bậc thầy",
    "Mana Tap": "Hút mana",
    "One Way Portal": "Cổng một chiều",
    "One-Way Portal": "Cổng một chiều",
    "Stable Portal": "Cổng ổn định",
    "Unnatural Growth": "Tăng trưởng phi tự nhiên",
    "Drinks on Me": "Ta mời rượu",
    "Call to Arms": "Hiệu triệu quân",
    "Divine Intervention": "Thiên sứ can thiệp",
    "Blessing of Protection": "Phước lành bảo hộ",
    "Prayers of Intercession": "Cầu nguyện cầu bầu",
    # Creatures
    "Ancient Skeleton": "Bộ xương cổ xưa",
    "Ancient Skeletons": "Bộ xương cổ xưa",
    "Ancient Treant": "Thụ nhân cổ xưa",
    "Ancient Treants": "Thụ nhân cổ xưa",
    "Bandit": "Thổ phỉ",
    "Bandits": "Thổ phỉ",
    "Giant Bat": "Dơi khổng lồ",
    "Giant Bats": "Dơi khổng lồ",
    "Beholder Spawn": "Con mắt dị loài",
    "Beholder Spawns": "Con mắt dị loài",
    "Corrupted Bandit": "Thổ phỉ tha hóa",
    "Corrupted Bandits": "Thổ phỉ tha hóa",
    "Dire Bat": "Dơi dữ",
    "Dire Bats": "Dơi dữ",
    "Sinister Eye": "Mắt hiểm ác",
    "Sinister Eyes": "Mắt hiểm ác",
    "Greater Sinister Eye": "Mắt hiểm ác lớn",
    "Greater Sinister Eyes": "Mắt hiểm ác lớn",
    "Giant Mosquito": "Muỗi khổng lồ",
    "Giant Mosquitoes": "Muỗi khổng lồ",
    "Giant Rat": "Chuột khổng lồ",
    "Giant Rats": "Chuột khổng lồ",
    "Goblin": "Goblin",
    "Goblins": "Goblin",
    "Goblin Raider": "Goblin cướp phá",
    "Goblin Raiders": "Goblin cướp phá",
    "Goblin Warrior": "Goblin chiến binh",
    "Goblin Warriors": "Goblin chiến binh",
    "Orc": "Orc",
    "Orcs": "Orc",
    "Orc Berserker": "Orc cuồng chiến",
    "Orc Berserkers": "Orc cuồng chiến",
    "Orc Warrior": "Orc chiến binh",
    "Orc Warriors": "Orc chiến binh",
    "Plague Mosquito": "Muỗi dịch",
    "Plague Mosquitoes": "Muỗi dịch",
    "Plague Rat": "Chuột dịch",
    "Plague Rats": "Chuột dịch",
    "Monstrous Mushroom": "Nấm quái",
    "Monstrous Mushrooms": "Nấm quái",
    "Shambling Plant": "Cây lê bước",
    "Shambling Plants": "Cây lê bước",
    "Huge Rat": "Chuột khổng lồ",
    "Huge Rats": "Chuột khổng lồ",
    "Ashenholt Soldier": "Binh sĩ Ashenholt",
    "Ashenholt Soldiers": "Binh sĩ Ashenholt",
    "Rotten Zombie": "Zombie thối rữa",
    "Rotten Zombies": "Zombie thối rữa",
    "Skeleton": "Bộ xương",
    "Skeletons": "Bộ xương",
    "Skeleton Warrior": "Bộ xương chiến binh",
    "Skeleton Warriors": "Bộ xương chiến binh",
    "[b]Spirit of Justice[/b]": "[b]Linh hồn công lý[/b]",
    "Spore Tyrant": "Bạo chúa bào tử",
    "Spore Tyrants": "Bạo chúa bào tử",
    "Thorned Plant": "Cây gai",
    "Thorned Plants": "Cây gai",
    "Toxic Mushroom": "Nấm độc",
    "Toxic Mushrooms": "Nấm độc",
    "Vampiric Bat": "Dơi hút máu",
    "Vampiric Bats": "Dơi hút máu",
    "Zombie": "Zombie",
    "Zombies": "Zombie",
    # Debuffs
    "Recently Raided": "Vừa bị cướp phá",
    # Tools / goods / training
    "Sturdy Tools": "Công cụ chắc chắn",
    "Steel Tools": "Công cụ thép",
    "Iron Tools": "Công cụ sắt",
    "Improved Steel Tools": "Công cụ thép cải tiến",
    "Improved Iron Tools": "Công cụ sắt cải tiến",
    "Premium Metalwork Trade Goods": "Hàng kim loại cao cấp",
    "Metalwork Trade Goods": "Hàng kim loại",
    "Quality Metalwork Trade Goods": "Hàng kim loại chất lượng",
    "Woodcrafting": "Chế tác gỗ",
    "Efficient Cuts": "Cắt gỗ hiệu quả",
    "Wooden Trade Goods": "Hàng gỗ",
    "Quality Wooden Trade Goods": "Hàng gỗ chất lượng",
    "Premium Wooden Trade Goods": "Hàng gỗ cao cấp",
    "Luxury Furniture Crafting": "Chế tác nội thất xa xỉ",
    "Consecrated Ground": "Đất thánh",
    "Social Welfare": "An sinh xã hội",
    "Sacred Ground": "Đất thiêng",
    "Consecrated Weapons": "Vũ khí thánh hóa",
    "Baptismal Font": "Giếng rửa tội",
    "Soup Kitchen": "Bếp từ thiện",
    "Tithes": "Thập phân",
    "Alms for the Poor": "Bố thí người nghèo",
    "Prayers of Protection": "Cầu nguyện bảo hộ",
    "Community Outreach": "Phục vụ cộng đồng",
    "Fishing Boats": "Thuyền đánh cá",
    "Premium Agrarian Trade Goods": "Hàng nông sản cao cấp",
    "Agrarian Trade Goods": "Hàng nông sản",
    "Quality Agrarian Trade Goods": "Hàng nông sản chất lượng",
    "Superior Weapons": "Vũ khí ưu việt",
    "Superior Armour": "Giáp ưu việt",
    "Specialised Training": "Huấn luyện chuyên biệt",
    "Premium Weapons": "Vũ khí cao cấp",
    "Premium Armour": "Giáp cao cấp",
    "Elite Training": "Huấn luyện tinh nhuệ",
    "Basic Weapons": "Vũ khí cơ bản",
    "Leather Armour": "Giáp da",
    "Basic Training": "Huấn luyện cơ bản",
    "Sturdy Weapons": "Vũ khí chắc chắn",
    "Sturdy Armour": "Giáp chắc chắn",
    "Martial Training": "Huấn luyện võ",
    "Quality Weapons": "Vũ khí chất lượng",
    "Quality Armour": "Giáp chất lượng",
    "Advanced Training": "Huấn luyện nâng cao",
    "Advanced Scouting": "Trinh sát nâng cao",
    "Steel Hunting Tools": "Dụng cụ săn thép",
    "Improved Steel Hunting Tools": "Dụng cụ săn thép cải tiến",
    "Sturdy Hunting Tools": "Dụng cụ săn chắc chắn",
    "Iron Hunting Tools": "Dụng cụ săn sắt",
    "Scouting": "Trinh sát",
    "Improved Iron Hunting Tools": "Dụng cụ săn sắt cải tiến",
    "Regal Aura": "Hào quang vương giả",
    "Construction Advisor": "Cố vấn xây dựng",
    "Research Advisor": "Cố vấn nghiên cứu",
    "Eye for Quality": "Con mắt tinh đời",
    "Force of Will": "Ý chí mạnh mẽ",
    "Shop Advisor": "Cố vấn cửa hàng",
    "Policy Advisor": "Cố vấn chính sách",
    "Trade Advisor": "Cố vấn giao thương",
    "Gifted Leader": "Lãnh đạo tài năng",
    "Supportive Spouse": "Phối ngẫu hỗ trợ",
    "Crown's Will": "Ý chí vương quyền",
    "Guild Training": "Huấn luyện hội thợ",
    "Leatherworking Techniques": "Kỹ thuật chế da",
    "Prospectors Tools": "Dụng cụ thợ thăm dò",
    "Workers' Leather Goods": "Đồ da cho nhân công",
    "Tanning Techniques": "Kỹ thuật thuộc da",
    "Luxury Trade Goods": "Hàng xa xỉ",
    "Sturdy Boots": "Giày chắc chắn",
    "Quality Luxury Trade Goods": "Hàng xa xỉ chất lượng",
    "Improved Leather Goods": "Đồ da cải tiến",
    "Dyeworks": "Xưởng nhuộm",
    "Premium Luxury Trade Goods": "Hàng xa xỉ cao cấp",
    "Fine Textiles": "Vải tinh",
    "Apprenticeships": "Học việc",
    "Basic Education": "Giáo dục cơ bản",
    "Advanced Building Design": "Thiết kế công trình nâng cao",
    "General Education": "Giáo dục phổ thông",
    "Expert Building Design": "Thiết kế công trình chuyên gia",
    "Higher Education": "Giáo dục cao cấp",
    "Master Building Design": "Thiết kế công trình bậc thầy",
    "Advanced Education": "Giáo dục nâng cao",
    "Legendary Building Design": "Thiết kế công trình huyền thoại",
    "Premium Magical Trade Goods": "Hàng phép thuật cao cấp",
    "Magic Repository": "Kho phép thuật",
    "Magical Trade Goods": "Hàng phép thuật",
    "Quality Magical Trade Goods": "Hàng phép thuật chất lượng",
    "Powerful Magical Equipment": "Trang bị phép mạnh",
    "Supreme Magical Equipment": "Trang bị phép tối thượng",
    "Sturdy Magical Equipment": "Trang bị phép chắc chắn",
    "Refined Magical Equipment": "Trang bị phép tinh chế",
    "Precise Magical Equipment": "Trang bị phép chính xác",
    "Royal Caravan": "Đoàn buôn hoàng gia",
    "Coinage": "Đúc tiền",
    "Money Lender": "Người cho vay",
    "Currency Exchange": "Đổi tiền",
    "Coin of the Realm": "Tiền vương quốc",
    "Fur and Leather Trade": "Buôn da và lông",
    "Market Day": "Ngày chợ",
    "Traders' Caravan": "Đoàn buôn thương nhân",
    "Caravan Upgrade": "Nâng cấp đoàn buôn",
    "Stone Trade Goods": "Hàng đá",
    "Quality Stone Trade Goods": "Hàng đá chất lượng",
    "Premium Stone Trade Goods": "Hàng đá cao cấp",
    "Extra Accommodation": "Chỗ ở thêm",
    "Hearty Meals": "Bữa ăn no đủ",
    "Quality Drinks": "Đồ uống chất lượng",
    "Premium Drinks": "Đồ uống cao cấp",
}


def translate_name(en: str) -> str | None:
    if en in _FIXED_NAMES:
        return _FIXED_NAMES[en]
    m = ROMAN.search(en)
    if m:
        base = en[: m.start()]
        roman = m.group(1)
        if base in _BASE_NAMES:
            return f"{_BASE_NAMES[base]} {roman}"
        if base in _FIXED_NAMES:
            return f"{_FIXED_NAMES[base]} {roman}"
    return None
